version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./setup/db:/docker-entrypoint-initdb.d/
    ports:
      - "6543:5432"
  rabbit-server:
    image: rabbitmq:3
    ports:
      -  "6783:5672"
