# Generated by Django 3.2.3 on 2021-05-29 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedportion',
            name='portion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_portions', to='catering.portion'),
        ),
    ]
