# Generated by Django 3.2.3 on 2021-05-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_auto_20210530_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='visit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
